In [131]:
import pickle
file_path = "E:\\python\\2.PROJECTS\\car sales prediction\\refrences\\elastic_poly_reg.pkl"
with open(file_path, 'rb') as f:
    model = pickle.load(f)
model

ElasticNetCV(cv=4, l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 0.995, 1],
             max_iter=100000)

In [132]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

# Split the data



In [133]:
data = {
    "Age": 5,
    # "Selling_Price": 3.35,
    "Present_Price": 5.59,
    "Kms_Driven": 27000,
    "Owner": 0,
    "Fuel_Type_Diesel": 1,
    "Fuel_Type_Petrol": 0,
    "Seller_Type_Individual": 1, # dealer 1 individual 0
    "Transmission_Manual": 1 # mannual 1 auto 1
}

In [134]:
# wagonr,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0

# 5	3.35	5.59	27000	Petrol	Dealer	Manual	0

data2 = {"Age": 5,
    # "Selling_Price": 3.35,
    "Present_Price": 5.59,
    "Kms_Driven": 27000,
    "Owner": 0,
    "Fuel_Type_Diesel": 0,
    "Fuel_Type_Petrol": 0,
    "Seller_Type_Individual": 1, # dealer 1 individual 0
    "Transmission_Manual":1 }# mannual 1 auto 1}

In [135]:
# 6	4.75	9.54	43000	Diesel	Dealer	Manual	0\

data3 ={"Age": 6,
    # "Selling_Price": 9.54,
    "Present_Price": 4.75,
    "Kms_Driven": 43000,
    "Owner": 0,
    "Fuel_Type_Diesel": 1,
    "Fuel_Type_Petrol": 0,
    "Seller_Type_Individual": 0, # dealer 1 individual 0
    "Transmission_Manual":1 }

In [136]:
user_ip: dict = {'Car_Name':'ritz',
                  'Year':2014,
                  'Selling_Price':3.35,
                  'Present_Price':5.59,
                  'Kms_Driven':27000,
                  'Fuel_Type':'Petrol',
                  'Seller_Type':'Dealer',
                  'Transmission':'Manual',
                  'Owner':0}

In [137]:
df = pd.DataFrame(data2,index=[0])
df

Age  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  Fuel_Type_Petrol  \
0    5           5.59       27000      0                 0                 0   

   Seller_Type_Individual  Transmission_Manual  
0                       1                    1

In [138]:
df.drop('Fuel_Type_Petrol',axis=1,inplace=True)

In [139]:
df.head()

Age  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  \
0    5           5.59       27000      0                 0   

   Seller_Type_Individual  Transmission_Manual  
0                       1                    1

In [140]:
import pickle
file_path = "E:\\python\\2.PROJECTS\\car sales prediction\\refrences\\poly_features.pkl"
with open(file_path, 'rb') as f:
    poly_features = pickle.load(f)
poly_features

PolynomialFeatures(degree=4, include_bias=False)

In [141]:
X_poly = poly_features.transform(df)
X_poly

array([[5.00000000e+00, 5.59000000e+00, 2.70000000e+04, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 1.00000000e+00, 2.50000000e+01,
        2.79500000e+01, 1.35000000e+05, 0.00000000e+00, 0.00000000e+00,
        5.00000000e+00, 5.00000000e+00, 3.12481000e+01, 1.50930000e+05,
        0.00000000e+00, 0.00000000e+00, 5.59000000e+00, 5.59000000e+00,
        7.29000000e+08, 0.00000000e+00, 0.00000000e+00, 2.70000000e+04,
        2.70000000e+04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.25000000e+02,
        1.39750000e+02, 6.75000000e+05, 0.00000000e+00, 0.00000000e+00,
        2.50000000e+01, 2.50000000e+01, 1.56240500e+02, 7.54650000e+05,
        0.00000000e+00, 0.00000000e+00, 2.79500000e+01, 2.79500000e+01,
        3.64500000e+09, 0.00000000e+00, 0.00000000e+00, 1.35000000e+05,
        1.35000000e+05, 0.00000000e+00, 0.00000000e+00, 0.000000

In [142]:
feature_names = poly_features.get_feature_names_out()

In [143]:
df_poly = pd.DataFrame(X_poly, columns=feature_names)

In [144]:
df_poly

Age  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  \
0  5.0           5.59     27000.0    0.0               0.0   

   Seller_Type_Individual  Transmission_Manual  Age^2  Age Present_Price  \
0                     1.0                  1.0   25.0              27.95   

   Age Kms_Driven  ...  Fuel_Type_Diesel^2 Transmission_Manual^2  \
0        135000.0  ...                                       0.0   

   Fuel_Type_Diesel Seller_Type_Individual^3  \
0                                        0.0   

   Fuel_Type_Diesel Seller_Type_Individual^2 Transmission_Manual  \
0                                                0.0               

   Fuel_Type_Diesel Seller_Type_Individual Transmission_Manual^2  \
0                                                0.0               

   Fuel_Type_Diesel Transmission_Manual^3  Seller_Type_Individual^4  \
0                                     0.0                       1.0   

   Seller_Type_Individual^3 Transmission_Manual  \
0                                           1.0   

   Seller_Type_Individual^2 Transmission_Manual^2  \
0                                             1.0   

   Seller_Type_Individual Transmission_Manual^3  Transmission_Manual^4  
0                                           1.0                    1.0  

[1 rows x 329 columns]

# remove the not required columns

In [145]:
specified_columns = ['Present_Price', 'Transmission_Manual', 'Seller_Type_Individual^2',
       'Age Seller_Type_Individual Transmission_Manual',
       'Kms_Driven Fuel_Type_Diesel Transmission_Manual', 'Age^4',
       'Age^2 Present_Price^2', 'Age^2 Owner Transmission_Manual',
       'Age^2 Fuel_Type_Diesel Seller_Type_Individual',
       'Age^2 Fuel_Type_Diesel Transmission_Manual',
       'Age Present_Price^2 Fuel_Type_Diesel',
       'Age Kms_Driven^2 Seller_Type_Individual', 'Present_Price^4',
       'Present_Price^2 Fuel_Type_Diesel Transmission_Manual',
       'Present_Price^2 Seller_Type_Individual Transmission_Manual',
       'Present_Price Kms_Driven^2 Owner',
       'Present_Price Kms_Driven Owner Transmission_Manual',
       'Present_Price Owner Seller_Type_Individual Transmission_Manual',
       'Kms_Driven^3 Fuel_Type_Diesel', 'Kms_Driven^3 Transmission_Manual']
df_poly = df_poly.reindex(columns=specified_columns, fill_value=0)



In [146]:
import pickle
file_path = "E:\\python\\2.PROJECTS\\car sales prediction\\refrences\\standard_scaler.pkl"
with open(file_path, 'rb') as f:
    scaler = pickle.load(f)
scaler

StandardScaler()

In [147]:
df = scaler.transform(df_poly)
df

array([[ 3.64776749e+00, -2.98976912e+00,  1.91636090e+01,
        -6.52231549e-01, -4.25505490e-01,  2.91871668e+02,
         9.53411414e+01, -1.93606811e-01, -6.93375245e-02,
        -4.17187817e-01, -4.34190832e-01,  1.18407260e+06,
         1.77018546e+01, -4.15042034e-01, -2.40100564e-01,
        -1.29573432e-01, -1.66398550e-01, -1.19733451e-01,
        -3.90843310e-01,  1.20493253e+04]])

In [130]:
df = pd.DataFrame(data2,index=[0]) # user input converted to dataframe
df.drop('Fuel_Type_Petrol',axis=1,inplace=True) # dropped 1 feaure 
X_poly = poly_features.transform(df) # loaded from a pickle model

feature_names = poly_features.get_feature_names_out()
df_poly = pd.DataFrame(X_poly, columns=feature_names) # created a new polynomial dataframe

df_poly = df_poly.loc[:, specified_columns] # some selective columns picked rest dropped

df = scaler.transform(df_poly) # scaler loaded from pickle transformed

new_df = pd.DataFrame(df, columns=specified_columns) # created a dataframe

result = model.predict(new_df) # model is elastic net cv

e:\python\2.PROJECTS\car sales prediction\carVENV\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but ElasticNetCV was fitted without feature names
  warnings.warn(


In [148]:
new_df = pd.DataFrame(df, columns=specified_columns)

In [149]:
new_df

Present_Price  Transmission_Manual  Seller_Type_Individual^2  \
0       3.647767            -2.989769                 19.163609   

   Age Seller_Type_Individual Transmission_Manual  \
0                                       -0.652232   

   Kms_Driven Fuel_Type_Diesel Transmission_Manual       Age^4  \
0                                        -0.425505  291.871668   

   Age^2 Present_Price^2  Age^2 Owner Transmission_Manual  \
0              95.341141                        -0.193607   

   Age^2 Fuel_Type_Diesel Seller_Type_Individual  \
0                                      -0.069338   

   Age^2 Fuel_Type_Diesel Transmission_Manual  \
0                                   -0.417188   

   Age Present_Price^2 Fuel_Type_Diesel  \
0                             -0.434191   

   Age Kms_Driven^2 Seller_Type_Individual  Present_Price^4  \
0                             1.184073e+06        17.701855   

   Present_Price^2 Fuel_Type_Diesel Transmission_Manual  \
0                                          -0.415042      

   Present_Price^2 Seller_Type_Individual Transmission_Manual  \
0                                          -0.240101            

   Present_Price Kms_Driven^2 Owner  \
0                         -0.129573   

   Present_Price Kms_Driven Owner Transmission_Manual  \
0                                          -0.166399    

   Present_Price Owner Seller_Type_Individual Transmission_Manual  \
0                                          -0.119733                

   Kms_Driven^3 Fuel_Type_Diesel  Kms_Driven^3 Transmission_Manual  
0                      -0.390843                      12049.325256

In [150]:
import pickle
file_path = "E:\\python\\2.PROJECTS\\car sales prediction\\refrences\\elastic_poly_reg.pkl"
with open(file_path, 'rb') as f:
    model = pickle.load(f)
model

ElasticNetCV(cv=4, l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 0.995, 1],
             max_iter=100000)

In [156]:
file_path = 'E:\\python\\2.PROJECTS\\car sales prediction\\artifacts\\rf_model.pkl'
with open(file_path, 'rb') as f:
    model = pickle.load(f)

In [151]:
result = model.predict(new_df)

e:\python\2.PROJECTS\car sales prediction\carVENV\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but ElasticNetCV was fitted without feature names
  warnings.warn(


In [152]:
result

array([10277.59465286])