In [16]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import scipy.stats as stats

# Split the data



In [59]:
fl = {
    'Age': -0.360231,
    'Selling_Price': -0.035121,
    'Present_Price': 0.078725,
    'Kms_Driven': 0.350131,
    'Owner': -30.152326,
    'Fuel_Type_Diesel': -7.293622,
    'Seller_Type_Individual': -2.570020,
    'Transmission_Manual': 14.351418,
    'Fuel_Type_Petrol': 6.887121
}
# fl.keys()
# fitted_lambda = pd.DataFrame(data=fl,index=fl.keys())
# fitted_lambda

# fitted_lambda = pd.Series(np.zeros(len(fl.keys()), dtype=np.float64), index=fl.keys())
fitted_lambda = pd.Series(data = fl.values(), index=fl.keys())
fitted_lambda

Age                       -0.360231
Selling_Price             -0.035121
Present_Price              0.078725
Kms_Driven                 0.350131
Owner                    -30.152326
Fuel_Type_Diesel          -7.293622
Seller_Type_Individual    -2.570020
Transmission_Manual       14.351418
Fuel_Type_Petrol           6.887121
dtype: float64

In [18]:
data = {
    "Age": 5,
    # "Selling_Price": 3.35,
    "Present_Price": 5.59,
    "Kms_Driven": 27000,
    "Owner": 0,
    "Fuel_Type_Diesel": 1,
    "Fuel_Type_Petrol": 0,
    "Seller_Type_Individual": 1, # dealer 1 individual 0
    "Transmission_Manual": 1 # mannual 1 auto 1
}

In [19]:
# wagonr,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0

# 5	3.35	5.59	27000	Petrol	Dealer	Manual	0

data2 = {"Age": 5,
    # "Selling_Price": 3.35,
    "Present_Price": 5.59,
    "Kms_Driven": 27000,
    "Owner": 0,
    "Fuel_Type_Diesel": 0,
    "Fuel_Type_Petrol": 0,
    "Seller_Type_Individual": 1, # dealer 1 individual 0
    "Transmission_Manual":1 }# mannual 1 auto 1}

In [135]:
# 6	4.75	9.54	43000	Diesel	Dealer	Manual	0\

data3 ={"Age": 6,
    # "Selling_Price": 9.54,
    "Present_Price": 4.75,
    "Kms_Driven": 43000,
    "Owner": 0,
    "Fuel_Type_Diesel": 1,
    "Fuel_Type_Petrol": 0,
    "Seller_Type_Individual": 0, # dealer 1 individual 0
    "Transmission_Manual":1 }

In [57]:
data4 =data_dict = {
    # "Car_Name": "ciaz",
    "Year": 2015,
    # "Selling_Price": 7.5,
    "Present_Price": 9.94,
    "Kms_Driven": 15000,
    "Fuel_Type": "Petrol",
    "Seller_Type": "Dealer",
    "Transmission": "Automatic",
    "Owner": 0
}

In [136]:
user_ip: dict = {'Car_Name':'ritz',
                  'Year':2014,
                  'Selling_Price':3.35,
                  'Present_Price':5.59,
                  'Kms_Driven':27000,
                  'Fuel_Type':'Petrol',
                  'Seller_Type':'Dealer',
                  'Transmission':'Manual',
                  'Owner':0}

In [58]:
df = pd.DataFrame(data4,index=[0])
df

Year  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0  2015           9.94       15000    Petrol      Dealer    Automatic      0

In [22]:
for col in df.columns:
    df[col] = stats.boxcox(df[col]+1, fitted_lambda[col])

In [23]:
df

Age  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  \
0  1.320186       2.032689   98.846722    0.0               0.0   

   Fuel_Type_Petrol  Seller_Type_Individual  Transmission_Manual  
0               0.0                0.323577          1456.437013

In [24]:
df.drop('Fuel_Type_Petrol',axis=1,inplace=True)

In [25]:
df.head()

Age  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  \
0  1.320186       2.032689   98.846722    0.0               0.0   

   Seller_Type_Individual  Transmission_Manual  
0                0.323577          1456.437013

In [28]:
import pickle
file_path = "E:\\python\\2.PROJECTS\\car sales prediction\\artifacts\\poly_features.pkl"
with open(file_path, 'rb') as f:
    poly_features = pickle.load(f)
poly_features

PolynomialFeatures(degree=4, include_bias=False)

In [29]:
X_poly = poly_features.transform(df)
X_poly

array([[1.32018646e+00, 2.03268862e+00, 9.88467224e+01, 0.00000000e+00,
        0.00000000e+00, 3.23576524e-01, 1.45643701e+03, 1.74289230e+00,
        2.68352800e+00, 1.30496105e+02, 0.00000000e+00, 0.00000000e+00,
        4.27181346e-01, 1.92276843e+03, 4.13182303e+00, 2.00924608e+02,
        0.00000000e+00, 0.00000000e+00, 6.57730318e-01, 2.96048294e+03,
        9.77067452e+03, 0.00000000e+00, 0.00000000e+00, 3.19844788e+01,
        1.43964025e+05, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.04701767e-01, 4.71268826e+02, 2.12120877e+06, 2.30094282e+00,
        3.54275734e+00, 1.72279191e+02, 0.00000000e+00, 0.00000000e+00,
        5.63959031e-01, 2.53841285e+03, 5.45477683e+00, 2.65257947e+02,
        0.00000000e+00, 0.00000000e+00, 8.68326662e-01, 3.90838950e+03,
        1.28991122e+04, 0.00000000e+00, 0.00000000e+00, 4.22254759e+01,
        1.90059357e+05, 0.00000000e+00, 0.00000000e+00, 0.000000

In [30]:
feature_names = poly_features.get_feature_names_out()

In [31]:
df_poly = pd.DataFrame(X_poly, columns=feature_names)

In [32]:
df_poly

Age  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  \
0  1.320186       2.032689   98.846722    0.0               0.0   

   Seller_Type_Individual  Transmission_Manual     Age^2  Age Present_Price  \
0                0.323577          1456.437013  1.742892           2.683528   

   Age Kms_Driven  ...  Fuel_Type_Diesel^2 Transmission_Manual^2  \
0      130.496105  ...                                       0.0   

   Fuel_Type_Diesel Seller_Type_Individual^3  \
0                                        0.0   

   Fuel_Type_Diesel Seller_Type_Individual^2 Transmission_Manual  \
0                                                0.0               

   Fuel_Type_Diesel Seller_Type_Individual Transmission_Manual^2  \
0                                                0.0               

   Fuel_Type_Diesel Transmission_Manual^3  Seller_Type_Individual^4  \
0                                     0.0                  0.010962   

   Seller_Type_Individual^3 Transmission_Manual  \
0                                     49.342679   

   Seller_Type_Individual^2 Transmission_Manual^2  \
0                                   222094.305933   

   Seller_Type_Individual Transmission_Manual^3  Transmission_Manual^4  
0                                  9.996596e+08           4.499527e+12  

[1 rows x 329 columns]

# remove the not required columns

In [33]:
specified_columns = ['Present_Price', 'Transmission_Manual', 'Seller_Type_Individual^2',
       'Age Seller_Type_Individual Transmission_Manual',
       'Kms_Driven Fuel_Type_Diesel Transmission_Manual', 'Age^4',
       'Age^2 Present_Price^2', 'Age^2 Owner Transmission_Manual',
       'Age^2 Fuel_Type_Diesel Seller_Type_Individual',
       'Age^2 Fuel_Type_Diesel Transmission_Manual',
       'Age Present_Price^2 Fuel_Type_Diesel',
       'Age Kms_Driven^2 Seller_Type_Individual', 'Present_Price^4',
       'Present_Price^2 Fuel_Type_Diesel Transmission_Manual',
       'Present_Price^2 Seller_Type_Individual Transmission_Manual',
       'Present_Price Kms_Driven^2 Owner',
       'Present_Price Kms_Driven Owner Transmission_Manual',
       'Present_Price Owner Seller_Type_Individual Transmission_Manual',
       'Kms_Driven^3 Fuel_Type_Diesel', 'Kms_Driven^3 Transmission_Manual']
df_poly = df_poly.reindex(columns=specified_columns, fill_value=0)



In [34]:
df_poly

Present_Price  Transmission_Manual  Seller_Type_Individual^2  \
0       2.032689          1456.437013                  0.104702   

   Age Seller_Type_Individual Transmission_Manual  \
0                                      622.162724   

   Kms_Driven Fuel_Type_Diesel Transmission_Manual     Age^4  \
0                                              0.0  3.037674   

   Age^2 Present_Price^2  Age^2 Owner Transmission_Manual  \
0               7.201323                              0.0   

   Age^2 Fuel_Type_Diesel Seller_Type_Individual  \
0                                            0.0   

   Age^2 Fuel_Type_Diesel Transmission_Manual  \
0                                         0.0   

   Age Present_Price^2 Fuel_Type_Diesel  \
0                                   0.0   

   Age Kms_Driven^2 Seller_Type_Individual  Present_Price^4  \
0                              4173.849898        17.071962   

   Present_Price^2 Fuel_Type_Diesel Transmission_Manual  \
0                                                0.0      

   Present_Price^2 Seller_Type_Individual Transmission_Manual  \
0                                        1947.199385            

   Present_Price Kms_Driven^2 Owner  \
0                               0.0   

   Present_Price Kms_Driven Owner Transmission_Manual  \
0                                                0.0    

   Present_Price Owner Seller_Type_Individual Transmission_Manual  \
0                                                0.0                

   Kms_Driven^3 Fuel_Type_Diesel  Kms_Driven^3 Transmission_Manual  
0                            0.0                      1.406626e+09

In [36]:
import pickle
file_path = "E:\\python\\2.PROJECTS\\car sales prediction\\artifacts\\standard_scaler.pkl"
with open(file_path, 'rb') as f:
    scaler = pickle.load(f)
scaler

StandardScaler()

In [49]:
df = scaler.transform(df_poly)
df[0]

array([ 0.12704453,  0.33421857,  1.33666245,  1.49605484, -0.42550549,
       -0.09037395, -0.11797526, -0.19360681, -0.06933752, -0.41718782,
       -0.43419083,  0.88620214, -0.37867927, -0.41504203,  6.7087212 ,
       -0.12957343, -0.16639855, -0.11973345, -0.39084331, -0.1578474 ])

In [51]:
df

array([[ 0.12704453,  0.33421857,  1.33666245,  1.49605484, -0.42550549,
        -0.09037395, -0.11797526, -0.19360681, -0.06933752, -0.41718782,
        -0.43419083,  0.88620214, -0.37867927, -0.41504203,  6.7087212 ,
        -0.12957343, -0.16639855, -0.11973345, -0.39084331, -0.1578474 ]])

In [52]:
new_df = pd.DataFrame(data = df, columns=df_poly.columns)

In [53]:
new_df

Present_Price  Transmission_Manual  Seller_Type_Individual^2  \
0       0.127045             0.334219                  1.336662   

   Age Seller_Type_Individual Transmission_Manual  \
0                                        1.496055   

   Kms_Driven Fuel_Type_Diesel Transmission_Manual     Age^4  \
0                                        -0.425505 -0.090374   

   Age^2 Present_Price^2  Age^2 Owner Transmission_Manual  \
0              -0.117975                        -0.193607   

   Age^2 Fuel_Type_Diesel Seller_Type_Individual  \
0                                      -0.069338   

   Age^2 Fuel_Type_Diesel Transmission_Manual  \
0                                   -0.417188   

   Age Present_Price^2 Fuel_Type_Diesel  \
0                             -0.434191   

   Age Kms_Driven^2 Seller_Type_Individual  Present_Price^4  \
0                                 0.886202        -0.378679   

   Present_Price^2 Fuel_Type_Diesel Transmission_Manual  \
0                                          -0.415042      

   Present_Price^2 Seller_Type_Individual Transmission_Manual  \
0                                           6.708721            

   Present_Price Kms_Driven^2 Owner  \
0                         -0.129573   

   Present_Price Kms_Driven Owner Transmission_Manual  \
0                                          -0.166399    

   Present_Price Owner Seller_Type_Individual Transmission_Manual  \
0                                          -0.119733                

   Kms_Driven^3 Fuel_Type_Diesel  Kms_Driven^3 Transmission_Manual  
0                      -0.390843                         -0.157847

In [54]:
import pickle
file_path = "E:\\python\\2.PROJECTS\\car sales prediction\\artifacts\\elastic_poly_reg.pkl"
with open(file_path, 'rb') as f:
    model = pickle.load(f)
model

ElasticNetCV(cv=4, l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 0.995, 1],
             max_iter=100000)

In [41]:
# file_path = 'E:\\python\\2.PROJECTS\\car sales prediction\\artifacts\\rf_model.pkl'
# with open(file_path, 'rb') as f:
#     model = pickle.load(f)

In [55]:
result = model.predict(df)

In [56]:
result

array([1.43298058])

In [62]:
import numpy as np
from scipy.special import inv_boxcox

In [63]:
x = inv_boxcox(result,fitted_lambda['Selling_Price'])

In [64]:
x

array([4.35052854])