In [65]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import scipy.stats as stats


In [66]:
fl = {
    'Age': -0.360231,
    'Selling_Price': -0.035121,
    'Present_Price': 0.078725,
    'Kms_Driven': 0.350131,
    'Owner': -30.152326,
    'Fuel_Type_Diesel': -7.293622,
    'Seller_Type_Individual': -2.570020,
    'Transmission_Manual': 14.351418,
    'Fuel_Type_Petrol': 6.887121
}
fitted_lambda = pd.Series(data = fl.values(), index=fl.keys())
fitted_lambda

Age                       -0.360231
Selling_Price             -0.035121
Present_Price              0.078725
Kms_Driven                 0.350131
Owner                    -30.152326
Fuel_Type_Diesel          -7.293622
Seller_Type_Individual    -2.570020
Transmission_Manual       14.351418
Fuel_Type_Petrol           6.887121
dtype: float64

In [67]:
# import pickle
# file_path = "E:\\python\\2.PROJECTS\\car sales prediction\\artifacts\\fitted_lambda.pkl"
# with open(file_path, 'wb') as f:
#     pickle.dump(fitted_lambda, f)

In [68]:
# file_path = "E:\\python\\2.PROJECTS\\car sales prediction\\artifacts\\fitted_lambda.pkl"
# with open(file_path, 'rb') as f:
#     lambdaaa = pickle.load(f)

In [83]:
# 6	4.75	9.54	43000	Diesel	Dealer	Manual	0\

data3 ={"Year": 2014,
    # "Selling_Price": 9.54,
    "Present_Price": 4.75,
    "Kms_Driven": 43000,
    "Owner": 0,
    "Fuel_Type_Diesel": 1,
    "Fuel_Type_Petrol": 0,
    "Seller_Type_Individual": 0, # dealer 1 individual 0
    "Transmission_Manual":1 }

In [84]:
df = pd.DataFrame(data3,index=[0])
df

Year  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  Fuel_Type_Petrol  \
0  2014           4.75       43000      0                 1                 0   

   Seller_Type_Individual  Transmission_Manual  
0                       0                    1

In [85]:
df.insert(0, "Age", 2019-df["Year"] )
df.drop(['Year','Fuel_Type_Petrol'],axis=1,inplace=True)

In [86]:
df

Age  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  \
0    5           4.75       43000      0                 1   

   Seller_Type_Individual  Transmission_Manual  
0                       0                    1

In [87]:
for col in df.columns:
    df[col] = stats.boxcox(df[col]+1, fitted_lambda[col])

In [88]:
df.head()

Age  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  \
0  1.320186       1.875361  116.843861    0.0          0.136232   

   Seller_Type_Individual  Transmission_Manual  
0                     0.0          1456.437013

In [89]:
import pickle
file_path = "E:\\python\\2.PROJECTS\\car sales prediction\\artifacts\\poly_features.pkl"
with open(file_path, 'rb') as f:
    poly_features = pickle.load(f)
poly_features

PolynomialFeatures(degree=4, include_bias=False)

In [90]:
X_poly = poly_features.transform(df)
X_poly

array([[1.32018646e+00, 1.87536130e+00, 1.16843861e+02, 0.00000000e+00,
        1.36232199e-01, 0.00000000e+00, 1.45643701e+03, 1.74289230e+00,
        2.47582660e+00, 1.54255684e+02, 0.00000000e+00, 1.79851905e-01,
        0.00000000e+00, 1.92276843e+03, 3.51697999e+00, 2.19124455e+02,
        0.00000000e+00, 2.55484593e-01, 0.00000000e+00, 2.73134560e+03,
        1.36524880e+04, 0.00000000e+00, 1.59178962e+01, 0.00000000e+00,
        1.70175725e+05, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.85592120e-02, 0.00000000e+00, 1.98413617e+02,
        0.00000000e+00, 0.00000000e+00, 2.12120877e+06, 2.30094282e+00,
        3.26855276e+00, 2.03646266e+02, 0.00000000e+00, 2.37438050e-01,
        0.00000000e+00, 2.53841285e+03, 4.64306937e+00, 2.89285140e+02,
        0.00000000e+00, 3.37287301e-01, 0.00000000e+00, 3.60588549e+03,
        1.80238298e+04, 0.00000000e+00, 2.10145910e+01, 0.00000000e+00,
        2.24663688e+05, 0.00000000e+00, 0.00000000e+00, 0.000000

In [91]:
feature_names = poly_features.get_feature_names_out()

In [92]:
df_poly = pd.DataFrame(X_poly, columns=feature_names)

In [93]:
df_poly

Age  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  \
0  1.320186       1.875361  116.843861    0.0          0.136232   

   Seller_Type_Individual  Transmission_Manual     Age^2  Age Present_Price  \
0                     0.0          1456.437013  1.742892           2.475827   

   Age Kms_Driven  ...  Fuel_Type_Diesel^2 Transmission_Manual^2  \
0      154.255684  ...                              39367.963272   

   Fuel_Type_Diesel Seller_Type_Individual^3  \
0                                        0.0   

   Fuel_Type_Diesel Seller_Type_Individual^2 Transmission_Manual  \
0                                                0.0               

   Fuel_Type_Diesel Seller_Type_Individual Transmission_Manual^2  \
0                                                0.0               

   Fuel_Type_Diesel Transmission_Manual^3  Seller_Type_Individual^4  \
0                            4.208767e+08                       0.0   

   Seller_Type_Individual^3 Transmission_Manual  \
0                                           0.0   

   Seller_Type_Individual^2 Transmission_Manual^2  \
0                                             0.0   

   Seller_Type_Individual Transmission_Manual^3  Transmission_Manual^4  
0                                           0.0           4.499527e+12  

[1 rows x 329 columns]

# remove the not required columns

In [94]:
specified_columns = ['Present_Price', 'Transmission_Manual', 'Seller_Type_Individual^2',
       'Age Seller_Type_Individual Transmission_Manual',
       'Kms_Driven Fuel_Type_Diesel Transmission_Manual', 'Age^4',
       'Age^2 Present_Price^2', 'Age^2 Owner Transmission_Manual',
       'Age^2 Fuel_Type_Diesel Seller_Type_Individual',
       'Age^2 Fuel_Type_Diesel Transmission_Manual',
       'Age Present_Price^2 Fuel_Type_Diesel',
       'Age Kms_Driven^2 Seller_Type_Individual', 'Present_Price^4',
       'Present_Price^2 Fuel_Type_Diesel Transmission_Manual',
       'Present_Price^2 Seller_Type_Individual Transmission_Manual',
       'Present_Price Kms_Driven^2 Owner',
       'Present_Price Kms_Driven Owner Transmission_Manual',
       'Present_Price Owner Seller_Type_Individual Transmission_Manual',
       'Kms_Driven^3 Fuel_Type_Diesel', 'Kms_Driven^3 Transmission_Manual']
df_poly = df_poly.reindex(columns=specified_columns, fill_value=0)



In [95]:
df_poly

Present_Price  Transmission_Manual  Seller_Type_Individual^2  \
0       1.875361          1456.437013                       0.0   

   Age Seller_Type_Individual Transmission_Manual  \
0                                             0.0   

   Kms_Driven Fuel_Type_Diesel Transmission_Manual     Age^4  \
0                                     23183.413143  3.037674   

   Age^2 Present_Price^2  Age^2 Owner Transmission_Manual  \
0               6.129717                              0.0   

   Age^2 Fuel_Type_Diesel Seller_Type_Individual  \
0                                            0.0   

   Age^2 Fuel_Type_Diesel Transmission_Manual  \
0                                  345.813564   

   Age Present_Price^2 Fuel_Type_Diesel  \
0                              0.632536   

   Age Kms_Driven^2 Seller_Type_Individual  Present_Price^4  \
0                                      0.0        12.369148   

   Present_Price^2 Fuel_Type_Diesel Transmission_Manual  \
0                                         697.816719      

   Present_Price^2 Seller_Type_Individual Transmission_Manual  \
0                                                0.0            

   Present_Price Kms_Driven^2 Owner  \
0                               0.0   

   Present_Price Kms_Driven Owner Transmission_Manual  \
0                                                0.0    

   Present_Price Owner Seller_Type_Individual Transmission_Manual  \
0                                                0.0                

   Kms_Driven^3 Fuel_Type_Diesel  Kms_Driven^3 Transmission_Manual  
0                  217318.885932                      2.323322e+09

In [96]:
import pickle
file_path = "E:\\python\\2.PROJECTS\\car sales prediction\\artifacts\\standard_scaler.pkl"
with open(file_path, 'rb') as f:
    scaler = pickle.load(f)
scaler

StandardScaler()

In [97]:
df = scaler.transform(df_poly)
df[0]

array([-0.02866462,  0.33421857, -0.748132  , -0.66963609,  2.20284196,
       -0.09037395, -0.25013847, -0.19360681, -0.06933752,  2.20778945,
        0.50135781, -0.46966707, -0.46730953,  0.87063939, -0.35343198,
       -0.12957343, -0.16639855, -0.11973345,  1.21223014,  0.40337331])

In [98]:
df

array([[-0.02866462,  0.33421857, -0.748132  , -0.66963609,  2.20284196,
        -0.09037395, -0.25013847, -0.19360681, -0.06933752,  2.20778945,
         0.50135781, -0.46966707, -0.46730953,  0.87063939, -0.35343198,
        -0.12957343, -0.16639855, -0.11973345,  1.21223014,  0.40337331]])

In [99]:
new_df = pd.DataFrame(data = df, columns=df_poly.columns)

In [100]:
new_df

Present_Price  Transmission_Manual  Seller_Type_Individual^2  \
0      -0.028665             0.334219                 -0.748132   

   Age Seller_Type_Individual Transmission_Manual  \
0                                       -0.669636   

   Kms_Driven Fuel_Type_Diesel Transmission_Manual     Age^4  \
0                                         2.202842 -0.090374   

   Age^2 Present_Price^2  Age^2 Owner Transmission_Manual  \
0              -0.250138                        -0.193607   

   Age^2 Fuel_Type_Diesel Seller_Type_Individual  \
0                                      -0.069338   

   Age^2 Fuel_Type_Diesel Transmission_Manual  \
0                                    2.207789   

   Age Present_Price^2 Fuel_Type_Diesel  \
0                              0.501358   

   Age Kms_Driven^2 Seller_Type_Individual  Present_Price^4  \
0                                -0.469667         -0.46731   

   Present_Price^2 Fuel_Type_Diesel Transmission_Manual  \
0                                           0.870639      

   Present_Price^2 Seller_Type_Individual Transmission_Manual  \
0                                          -0.353432            

   Present_Price Kms_Driven^2 Owner  \
0                         -0.129573   

   Present_Price Kms_Driven Owner Transmission_Manual  \
0                                          -0.166399    

   Present_Price Owner Seller_Type_Individual Transmission_Manual  \
0                                          -0.119733                

   Kms_Driven^3 Fuel_Type_Diesel  Kms_Driven^3 Transmission_Manual  
0                        1.21223                          0.403373

In [101]:
import pickle
file_path = "E:\\python\\2.PROJECTS\\car sales prediction\\artifacts\\elastic_poly_reg.pkl"
with open(file_path, 'rb') as f:
    model = pickle.load(f)
model

ElasticNetCV(cv=4, l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 0.995, 1],
             max_iter=100000)

In [41]:
# file_path = 'E:\\python\\2.PROJECTS\\car sales prediction\\artifacts\\rf_model.pkl'
# with open(file_path, 'rb') as f:
#     model = pickle.load(f)

In [102]:
result = model.predict(df)

In [103]:
result

array([1.43916345])

In [104]:
import numpy as np
from scipy.special import inv_boxcox

In [105]:
x = inv_boxcox(result,fitted_lambda['Selling_Price'])

In [106]:
x

array([4.37894844])